### PR TITLE
Improve docker and docker-compose

### PR DESCRIPTION
**Pull request by mtrimolet**
* Dockerfiles are now split in 3 parts : proto build, app build, app bundle
* bootstrap.yamls now use env vars to set services hostnames
* Dependency services added to docker-compose.dev.yaml

Fixes : #94

### CODE REVIEW

**Comment by juicycleff** [comment]
@mtrimolet while I merged in please try to see if kompose supports multistep docker yet. Kompose generates kubernetes deployment from docker-compose :)

**Comment by juicycleff** [comment]
@mtrimolet disregard I believe it's fine

**Comment by juicycleff** [comment]
@mtrimolet I just tested this in production environment and the proto files are missing, that's why I wrote the docker files as it was. And using the dockerignore script I just add reduces the size to 400mb which is close to what you did which was around 321.96 MiB, still better. If you can improve on it, I leave your current implementation else I would have to revert the docker files

**Comment by mtrimolet** [comment]
At which command are they missing ? At runtime ?

**Comment by juicycleff** [comment]
@mtrimolet at runtime

**Comment by juicycleff** [comment]
I had similar issue at runtime, so I made it simple and stuck with dockerignore, which works very well

**Pull request merged**
