### PR TITLE
Add missing build arguments to dev env

### PR DESCRIPTION
**Pull request by mtrimolet**
Following the README and running the command `docker-compose --project-directory=. -f docker-compose.dev.yml up --build`, you'll get yarn related errors. This is easily fixed by correctly setting the NODE_ENV to development (I suppose it impacts yarn behavior).
Other errors still appear but relates to per service concerns.

### CODE REVIEW

**Comment by juicycleff** [comment]
@mtrimolet thanks, I had similar experience with yarn in docker just yesterday

**Comment by mtrimolet** [comment]
I'm new to GitHub automations. I've set Codacy analysis on my patch branch, is there something else I need to do ?

**Comment by juicycleff** [comment]
@mtrimolet sorry GitHub was down for a bit. I too I'm new with Github Automations

**Comment by mtrimolet** [comment]
We'll sort it out 😄

**Pull request merged**
